version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
    environment:
      NODE_ENV: development
      PORT: 8000
    ports:
      - "8000:8000"
    volumes:
      - .:/app/

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evenhour
    volumes:
      - database-data:/var/lib/postgresql/data
  redis:
    image: redis
    container_name: cache
    expose:
      - 6379

volumes:
  database-data: