version: "3"
services:
  app:
    build: .
    depends_on:
      - postgres
    environment:
      NODE_ENV: development
      PORT: 4000
    ports:
      - "4000:4000"
    command: yarn start
    volumes:
      - .:/app/

  postgres:
    image: postgres:10
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: evenhour
    volumes:
      - database-data:/var/lib/postgresql/data

volumes:
  database-data: